## 개발 환경 전용 설정
spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: never

## p6spy - 개발 환경에서만 활성화
decorator:
  datasource:
    p6spy:
      enable-logging: on

## 개발 로그 레벨
logging:
  level:
    root: info
    web: debug
    com.peopleground: debug
    org.flywaydb: debug
